{{- if or (not .Values.config.truefoundry.existingSecret) (and (not .Values.config.qdrant.existingSecret) .Values.config.qdrant.apiKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-app.fullname" . }}
  labels:
    {{- include "rag-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.config.truefoundry.existingSecret }}
  TFY_API_KEY: {{ .Values.config.truefoundry.apiKey | quote }}
  {{- end }}
  {{- if and (not .Values.config.qdrant.existingSecret) .Values.config.qdrant.apiKey }}
  QDRANT_API_KEY: {{ .Values.config.qdrant.apiKey | quote }}
  {{- end }}
{{- end }}
