channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=24.2
- pip:
  - mlflow==3.1.0rc0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.2.3
  - scipy==1.14.1
  - vadersentiment==3.3.2
name: mlflow-env
