name: churn-prediction-train
type: job
image:
  type: build
  build_spec:
    type: tfy-python-buildpack
    command: >-
      python main.py --n_neighbors {{n_neighbors}} --weights {{weights}}
    python_version: '3.9'
    requirements_path: requirements.txt
    build_context_path: ./
  build_source:
    type: local
params:
  - name: n_neighbors
    default: '5'
    param_type: string
    description: Number of neighbors to use by default
  - name: weights
    default: uniform
    param_type: string
    description: 'Weight function used in prediction.  Possible values: uniform, distance'
retries: 0
trigger:
  type: manual
resources:
  cpu_limit: 1
  gpu_count: 0
  cpu_request: 1
  memory_limit: 2000
  memory_request: 2000
  ephemeral_storage_limit: 2000
  ephemeral_storage_request: 1000
env:
  TFY_API_KEY: paste api key here
